project:
  type: website
  output-dir: docs
execute:
  daemon: 600000
website:
  title: "AthulSudheesh"
  navbar: 
    right:
      - text: "About"
        href: https://athulsudheesh.com
      - icon: github
        href: https://github.com/athulsudheesh
      - icon: twitter
        href: https://twitter.com/athulsudheesh
format:
  html:
    comments:
          utterances:
              repo: athulsudheesh/athulsudheesh.github.io
    theme: 
      - journal
        - background:black
      - custom.scss
    css: styles.css